FROM ubuntu

#Run container interactively
# - docker run -it TAG bash

#Update ubuntu first:
# - apt-get update
# - apt-get upgrade
#Install the sql server:
# - apt install mysql-server
# - mysql_secure_installation

CMD bash
